// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBcGiNyiEwoM_OXXe0ljPh3_Hp-wVXNE',
    appId: '1:731482186199:web:b13410cc57a4fe3018eb92',
    messagingSenderId: '731482186199',
    projectId: 'alphabit-cell',
    authDomain: 'alphabit-cell.firebaseapp.com',
    storageBucket: 'alphabit-cell.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAx6OgxSCXftBIq6u-lAWutxGQkjUg5rk',
    appId: '1:731482186199:android:6980199a9b26aa6818eb92',
    messagingSenderId: '731482186199',
    projectId: 'alphabit-cell',
    storageBucket: 'alphabit-cell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjk_SzSX9vCdqkHTqASTQwawgb8hv-5n8',
    appId: '1:731482186199:ios:c4e48e3c63fb18a918eb92',
    messagingSenderId: '731482186199',
    projectId: 'alphabit-cell',
    storageBucket: 'alphabit-cell.appspot.com',
    iosBundleId: 'com.example.firstSession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjk_SzSX9vCdqkHTqASTQwawgb8hv-5n8',
    appId: '1:731482186199:ios:17d3bdc9f95a469f18eb92',
    messagingSenderId: '731482186199',
    projectId: 'alphabit-cell',
    storageBucket: 'alphabit-cell.appspot.com',
    iosBundleId: 'com.example.firstSession.RunnerTests',
  );
}
